version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./ # 도커파일 위치 명시
    image: frontend-dev-green
    container_name: frontend-dev-green
    ports:
      - 3001:3000
    stdin_open: true
