spring:
  datasource:
    url: jdbc:mysql://cozytrain.ckacazfcovre.ap-northeast-2.rds.amazonaws.com:3306/test_train
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ssafy1793
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  servlet:
    context-path: /api
