spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  token:
    secret-key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    com.ssafy: DEBUG