version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./
      args:
        TZ: Asia/Seoul
    ports:
      - "8589:8080"
    image: backend
    environment:
      - TZ=Asia/Seoul
    container_name: backend-blue
    stdin_open: true