version: '3.3'
services:
  backend-dev:
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./
      args:
        TZ: Asia/Seoul
    ports:
      - "8589:8080"
    networks:
      - backend-dev
    image: backend-dev-blue:latest
    environment:
      - TZ=Asia/Seoul
    container_name: backend-dev-blue
    stdin_open: true

networks:
  backend-dev:
    external: true