version: '3'
services:
  backend-prod:
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./
      args:
        TZ: Asia/Seoul
    ports:
      - "8699:8080"
#    image: backend-prod-green
    environment:
      - TZ=Asia/Seoul
    container_name: backend-prod-green
    stdin_open: true