version: '3'
services:
  backend-dev:
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./
      args:
        TZ: Asia/Seoul
    ports:
      - "8599:8080"
    image: backend-dev-green
    environment:
      - TZ=Asia/Seoul
    container_name: backend-dev-green
    stdin_open: true